bind = "127.0.0.1:5000"
workers = 1
worker_class = "gevent"
worker_connections = 1000
timeout = 30
keepalive = 2
max_requests = 1000
max_requests_jitter = 100
preload_app = True
daemon = False
pidfile = "/tmp/gunicorn.pid"
user = "raspberrypi"
group = "raspberrypi"
tmp_upload_dir = None
logfile = "/var/log/gunicorn/battery_twin.log"
loglevel = "info"
access_logfile = "/var/log/gunicorn/battery_twin_access.log"
access_logformat = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
